### ISSUE TITLE
Ground Station

### ISSUE THREAD

**Issue by gellings** [BYU-MAGICC/ros_plane#48]
How do we want to point people to the ground station?  Should we have a link in the readme (since the readme needs updating anyway)?  For reference, it is currently at https://github.com/goromal/ros_groundstation  We could make it a submodule here, make them both a submodule to another repo, or something else.  Any other ideas?

**Comment by goromal** [comment]
I think a "minimalist workspace" for getting the ground station running with rosplane, having rosplane, rosflight, and the groundstation as submodules, would be useful for people wanting to get a quick start.

**Comment by wynn4** [comment]
I think I agree with @goromal.  I think what we should do is provide a link in the ROSplane readme to the groundstation, and then in the groundstation readme, include instructions that tell people that they need to build the groundstation package inside a workspace that contains both the rosflight and rosplane packages.  I think this makes sense because this way, people will find out about the groundstation through the rosplane readme, and then if they've been using it and running the sim and stuff, then they just need to add the groundstation to their workspace and catkin_make

**Comment by gellings** [comment]
I'm going to call the byu-uav-class/rosplane_ws a good solution to this for now.
